[profile.default]
src = "src"
out = "out"
libs = ["lib"]
dotenv = true


[[profile.default.fs_permissions]]
access = "write"
path = "deployments"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
